name: main
on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat:"

    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.version.outputs.version_tag }}",
            sha: context.sha
          })

    # - name: Checkout prod
    #   uses: actions/checkout@v2
    #   with:
    #     repository: ${{ secrets.GH_ORG }}/todo-prod
    #     persist-credentials: false
    #     fetch-depth: 0
    # - name: Update manifests
    #   run: |
    #     sleep 1
    #     cat apps/${{ github.repo }}/overlays/staging/kustomization.yaml | sed -e "s@- cloudnativeentrepreneur/${{ github.repo }}:.*@- cloudnativeentrepreneur/${{ github.repo }}:${{ github.sha }}@g" | tee apps/${{ github.repo }}/overlays/staging/kustomization.yaml
    #     git config --global user.email "${{ secrets.GH_ORG }}@cloudnativeentrepreneur.com"
    #     git config --global user.name "${{ secrets.GH_ORG }}"
    #     git add .
    #     git commit -m "Promoting ${{ github.repo }} ${{ github.sha }}"
    # - name: Push prod
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GH_TOKEN }}
    #     repository: ${{ secrets.GH_ORG }}/todo-prod
 