name: main
on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Application Version
      id: version
      uses: paulhatch/semantic-version@v4.0.2
      with:
        major_pattern: "BREAKING CHANGE"
        minor_pattern: "feat:"

    - name: Create tag
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.git.createRef({
            owner: context.repo.owner,
            repo: context.repo.repo,
            ref: "refs/tags/${{ steps.version.outputs.version_tag }}",
            sha: context.sha
          })

    - name: Update version in manifest
      run: |
        sleep 1
        cat charts/example-hasura/values.yaml | sed -e "s@- latest@- ${{ steps.version.outputs.version_tag }}@g" | tee charts/example-hasura/values.yaml
        git config --global user.name "${{ github.actor }}"
        git add .
        git commit -m "chore: set version to ${{ steps.version.outputs.version_tag }}"
    
    - name: Push prod
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GH_TOKEN }}
        repository: ${{ github.repository }}
        tags: true
