name: main
on:
  push:
    branches:
    - main
jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    # used to run builders for architectures other than the host
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: ${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ steps.meta.outputs.tags }}
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache
        cache-to: type=registry,ref=ghcr.io/${{ github.repository }}:buildcache,mode=max

    # - name: Checkout prod
    #   uses: actions/checkout@v2
    #   with:
    #     repository: ${{ secrets.GH_ORG }}/todo-prod
    #     persist-credentials: false
    #     fetch-depth: 0
    # - name: Update manifests
    #   run: |
    #     sleep 1
    #     cat apps/${{ github.repo }}/overlays/staging/kustomization.yaml | sed -e "s@- cloudnativeentrepreneur/${{ github.repo }}:.*@- cloudnativeentrepreneur/${{ github.repo }}:${{ github.sha }}@g" | tee apps/${{ github.repo }}/overlays/staging/kustomization.yaml
    #     git config --global user.email "${{ secrets.GH_ORG }}@cloudnativeentrepreneur.com"
    #     git config --global user.name "${{ secrets.GH_ORG }}"
    #     git add .
    #     git commit -m "Promoting ${{ github.repo }} ${{ github.sha }}"
    # - name: Push prod
    #   uses: ad-m/github-push-action@master
    #   with:
    #     github_token: ${{ secrets.GH_TOKEN }}
    #     repository: ${{ secrets.GH_ORG }}/todo-prod
 