name: release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

        # used to run builders for architectures other than the host
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: cloudnativeentrepreneur/example-hasura

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.meta.outputs.tags }}
            ghcr.io/cloudnativeentrepreneur/example-hasura:latest
            ghcr.io/cloudnativeentrepreneur/example-hasura:${{ github.sha }}
            ghcr.io/cloudnativeentrepreneur/example-hasura:${{ steps.version.outputs.version }}
            ghcr.io/cloudnativeentrepreneur/example-hasura:${{ steps.version.outputs.version_tag }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/cloudnativeentrepreneur/example-hasura:buildcache
          cache-to: type=registry,ref=ghcr.io/cloudnativeentrepreneur/example-hasura:buildcache,mode=max

      - name: Release
        uses: softprops/action-gh-release@v1
